theme: jekyll-theme-slate
github:
    is_project_page: false
title: Pascal's Wurld
description: Miscellaneous JP translations   
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]